name: Update Snake SVG Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Replace the content of the SVG file
      - name: Update Snake SVG
        run: |
          echo "Updating Snake SVG..."
          echo '<svg viewBox="-16 -32 880 192" width="880" height="192" xmlns="http://www.w3.org/2000/svg"><style>@keyframes c0{1.43%{fill:var(--c1)}1.45%,to{fill:var(--ce)}}@keyframes c1{1.63%{fill:var(--c1)}1.65%,to{fill:var(--ce)}}@keyframes c2{1.84%{fill:var(--c1)}1.86%,to{fill:var(--ce)}}@keyframes c3{2.04%{fill:var(--c1)}2.06%,to{fill:var(--ce)}}@keyframes c4{2.25%{fill:var(--c1)}2.27%,to{fill:var(--ce)}}@keyframes c5{.81%{fill:var(--c1)}.83%,to{fill:var(--ce)}}@keyframes c6{3.69%{fill:var(--c1)}3.71%,to{fill:var(--ce)}}@keyframes c7{3.48%{fill:var(--c1)}3.5%,to{fill:var(--ce)}}@keyframes c8{4.51%{fill:var(--c1)}4.53%,to{fill:var(--ce)}}@keyframes c9{4.92%{fill:var(--c1)}4.94%,to{fill:var(--ce)}}@keyframes ca{68.78%{fill:var(--c2)}68.8%,to{fill:var(--ce)}}@keyframes cb{7.18%{fill:var(--c1)}7.2%,to{fill:var(--ce)}}@keyframes cc{7.38%{fill:var(--c1)}7.4%,to{fill:var(--ce)}}@keyframes cd{7.79%{fill:var(--c1)}7.81%,to{fill:var(--ce)}}@keyframes ce{68.16%{fill:var(--c2)}68.18%,to{fill:var(--ce)}}@keyframes cf{14.57%{fill:var(--c1)}14.59%,to{fill:var(--ce)}}@keyframes cg{14.77%{fill:var(--c1)}14.79%,to{fill:var(--ce)}}@keyframes ch{70.01%{fill:var(--c3)}70.03%,to{fill:var(--ce)}}@keyframes ci{67.14%{fill:var(--c2)}67.16%,to{fill:var(--ce)}}@keyframes cj{9.02%{fill:var(--c1)}9.04%,to{fill:var(--ce)}}@keyframes ck{93.21%{fill:var(--c4)}93.23%,to{fill:var(--ce)}}@keyframes cl{65.49%{fill:var(--c2)}65.51%,to{fill:var(--ce)}}@keyframes cm{65.7%{fill:var(--c2)}65.72%,to{fill:var(--ce)}}@keyframes cn{9.23%{fill:var(--c1)}9.25%,to{fill:var(--ce)}}@keyframes co{70.83%{fill:var(--c3)}70.85%,to{fill:var(--ce)}}@keyframes cp{66.11%{fill:var(--c2)}66.13%,to{fill:var(--ce)}}@keyframes cq{9.64%{fill:var(--c1)}9.66%,to{fill:var(--ce)}}@keyframes cr{9.85%{fill:var(--c1)}9.87%,to{fill:var(--ce)}}@keyframes cs{10.26%{fill:var(--c1)}10.28%,to{fill:var(--ce)}}@keyframes ct{64.88%{fill:var(--c2)}64.9%,to{fill:var(--ce)}}@keyframes cu{64.26%{fill:var(--c2)}64.28%,to{fill:var(--ce)}}<rest of your SVG content here>' > assets/github-contribution-grid-snake.svg

      # Step 3: Commit and push the updated SVG
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/github-contribution-grid-snake.svg
          git commit -m "Daily update: Snake SVG"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
